### ISSUE TITLE
Installation Instructions not clear to me, need more details

### ISSUE THREAD

**Issue by greatidea1** [vitalidze/traccar-web-docker#1]
Hi Vitalidze,
I'm new to Docker, but I'm able to pull and run Traccar original images on my VPS, but not yours. May you please mention the "How to use this image" section and detail the 'docker run' commands for your image?
Being a newbie, I could run a lot of images but I think your page lacks a few vital instructions, or sorry I'm missing something. Can you please help?
I have first pulled your image using the cmd: 'docker pull vitalidze/traccar-web'
I have tried below on my DigitalOcean VPS, but this always results in an exit code
 docker run -d --name traccar-web docker -p 8082:8082 vitalidze/traccar-web 

Even tried the "Using docker-compose", but unable to follow what the guide is suggesting

**Comment by vitalidze** [comment]
Hi

Me myself prefer running docker containers using `docker-compose`. I did tested it several times and it works just fine for me. You need to just download the `docker-compose.yml` file and then run the `docker-compose up -d` from the folder, where you downloaded the file.

To run it via `docker run` you need to just issue the following command:

```bash
docker run -d --name traccar-web -p 8082:8082 vitalidze/traccar-web
```

Then it should work just fine. If it does not work for you then please send console output that you see. Also please check logs of the service using the `docker logs traccar-web` command.
